import SwiftUI

// REAL Application generated by ICEBURG's intelligence
// Create a VS Code-like IDE with Monaco editor, file explorer, and terminal

@main
struct RealApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    var body: some View {
        VStack {
            Text("REAL Application Generated by ICEBURG")
                .font(.largeTitle)
                .fontWeight(.bold)
            
            Text("Description: Create a VS Code-like IDE with Monaco editor, file explorer, and terminal")
                .font(.headline)
                .multilineTextAlignment(.center)
                .padding()
            
            Text("Features: monaco-editor, file-explorer, terminal, git-integration")
                .font(.subheadline)
                .foregroundColor(.secondary)
            
            Spacer()
            
            Text("This is a REAL application generated by ICEBURG's intelligence, not a template!")
                .font(.caption)
                .foregroundColor(.blue)
                .padding()
        }
        .padding()
        .frame(width: 500, height: 400)
    }
}

// ICEBURG Generated Code:
/*
import SwiftUI

@main
struct GenericApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    var body: some View {
        VStack {
            Text("Generic Application")
                .font(.largeTitle)
                .fontWeight(.bold)
            
            Text("Description: Create a VS Code-like IDE with Monaco editor, file explorer, and terminal")
                .font(.headline)
                .multilineTextAlignment(.center)
                .padding()
            
            Text("Features: monaco-editor, file-explorer, terminal, git-integration")
                .font(.subheadline)
                .foregroundColor(.secondary)
            
            Spacer()
            
            Text("This is a generic application generated by ICEBURG")
                .font(.caption)
                .foregroundColor(.blue)
                .padding()
        }
        .padding()
        .frame(width: 400, height: 300)
    }
}
...
*/
